version: '3'

services:
  pg:
    image: postgres:10.4-alpine
    restart: always
    ports:
    - 5432
    volumes:
    - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "postgrespass"
      POSTGRES_DB: "postgresdb"
  redis:
    image: redis:4-alpine
    ports:
    - 6379
    volumes:
    - ./redis:/data
    command: >
     --requirepass redispass
  test:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - pg
    - redis
    ports:
    - "3000:8000"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - "./config:/config"
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      DB_NAME: "postgresdb"
      DB_USER: "postgresuser"
      DB_PASSWORD: "postgrespass"
      DB_HOST: "pg"
      DB_PORT: "5432"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redispass"
      SECRET_KEY: "secret"
      ALLOWED_HOSTS: "*"
